spring:
  application:
    name: rose-example-account
  profiles:
    active: development
---
server:
  port: 5001
  
---
spring:
  profiles: development
  
logging:
  level:
    logger.root: INFO
    com.tazhi.rose: DEBUG
    
mongodb:
  eventstore:
    host: localhost
    port: 27017
    database: event_sourcing
  snapshot:
    host: localhost
    port: 27017
    database: event_sourcing
    
kafka:
  eventbus:
      bootstrapServers: localhost:9092
      